name: Node.js CI
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - run: yarn lint
    - run: yarn test:ci
